//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabCOF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Graficos : global::System.Configuration.ApplicationSettingsBase {
        
        private static Graficos defaultInstance = ((Graficos)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Graficos())));
        
        public static Graficos Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool E0activo {
            get {
                return ((bool)(this["E0activo"]));
            }
            set {
                this["E0activo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Entrada 0")]
        public string E0name {
            get {
                return ((string)(this["E0name"]));
            }
            set {
                this["E0name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tiempo")]
        public string E0x {
            get {
                return ((string)(this["E0x"]));
            }
            set {
                this["E0x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E0")]
        public string E0y {
            get {
                return ((string)(this["E0y"]));
            }
            set {
                this["E0y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y1")]
        public string E0mostrar {
            get {
                return ((string)(this["E0mostrar"]));
            }
            set {
                this["E0mostrar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color E0color {
            get {
                return ((global::System.Drawing.Color)(this["E0color"]));
            }
            set {
                this["E0color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool E1activo {
            get {
                return ((bool)(this["E1activo"]));
            }
            set {
                this["E1activo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Entrada 1")]
        public string E1name {
            get {
                return ((string)(this["E1name"]));
            }
            set {
                this["E1name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tiempo")]
        public string E1x {
            get {
                return ((string)(this["E1x"]));
            }
            set {
                this["E1x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E1")]
        public string E1y {
            get {
                return ((string)(this["E1y"]));
            }
            set {
                this["E1y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y1")]
        public string E1mostrar {
            get {
                return ((string)(this["E1mostrar"]));
            }
            set {
                this["E1mostrar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color E1color {
            get {
                return ((global::System.Drawing.Color)(this["E1color"]));
            }
            set {
                this["E1color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool E2activo {
            get {
                return ((bool)(this["E2activo"]));
            }
            set {
                this["E2activo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Entrada 2")]
        public string E2name {
            get {
                return ((string)(this["E2name"]));
            }
            set {
                this["E2name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tiempo")]
        public string E2x {
            get {
                return ((string)(this["E2x"]));
            }
            set {
                this["E2x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E2")]
        public string E2y {
            get {
                return ((string)(this["E2y"]));
            }
            set {
                this["E2y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y1")]
        public string E2mostrar {
            get {
                return ((string)(this["E2mostrar"]));
            }
            set {
                this["E2mostrar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color E2color {
            get {
                return ((global::System.Drawing.Color)(this["E2color"]));
            }
            set {
                this["E2color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool E3activo {
            get {
                return ((bool)(this["E3activo"]));
            }
            set {
                this["E3activo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Entrada 3")]
        public string E3name {
            get {
                return ((string)(this["E3name"]));
            }
            set {
                this["E3name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tiempo")]
        public string E3x {
            get {
                return ((string)(this["E3x"]));
            }
            set {
                this["E3x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E3")]
        public string E3y {
            get {
                return ((string)(this["E3y"]));
            }
            set {
                this["E3y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y1")]
        public string E3mostrar {
            get {
                return ((string)(this["E3mostrar"]));
            }
            set {
                this["E3mostrar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color E3color {
            get {
                return ((global::System.Drawing.Color)(this["E3color"]));
            }
            set {
                this["E3color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool E4activo {
            get {
                return ((bool)(this["E4activo"]));
            }
            set {
                this["E4activo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Entrada 4")]
        public string E4name {
            get {
                return ((string)(this["E4name"]));
            }
            set {
                this["E4name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tiempo")]
        public string E4x {
            get {
                return ((string)(this["E4x"]));
            }
            set {
                this["E4x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E4")]
        public string E4y {
            get {
                return ((string)(this["E4y"]));
            }
            set {
                this["E4y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y1")]
        public string E4mostrar {
            get {
                return ((string)(this["E4mostrar"]));
            }
            set {
                this["E4mostrar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color E4color {
            get {
                return ((global::System.Drawing.Color)(this["E4color"]));
            }
            set {
                this["E4color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool E5activo {
            get {
                return ((bool)(this["E5activo"]));
            }
            set {
                this["E5activo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Entrada 5")]
        public string E5name {
            get {
                return ((string)(this["E5name"]));
            }
            set {
                this["E5name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tiempo")]
        public string E5x {
            get {
                return ((string)(this["E5x"]));
            }
            set {
                this["E5x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E5")]
        public string E5y {
            get {
                return ((string)(this["E5y"]));
            }
            set {
                this["E5y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y1")]
        public string E5mostrar {
            get {
                return ((string)(this["E5mostrar"]));
            }
            set {
                this["E5mostrar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fuchsia")]
        public global::System.Drawing.Color E5color {
            get {
                return ((global::System.Drawing.Color)(this["E5color"]));
            }
            set {
                this["E5color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Panel2Activo {
            get {
                return ((bool)(this["Panel2Activo"]));
            }
            set {
                this["Panel2Activo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ActivoY2panel1 {
            get {
                return ((bool)(this["ActivoY2panel1"]));
            }
            set {
                this["ActivoY2panel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ActivoY2panel2 {
            get {
                return ((bool)(this["ActivoY2panel2"]));
            }
            set {
                this["ActivoY2panel2"] = value;
            }
        }
    }
}
