//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabCOF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SettingsBluetooth : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBluetooth defaultInstance = ((SettingsBluetooth)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBluetooth())));
        
        public static SettingsBluetooth Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TimeRcepcion {
            get {
                return ((int)(this["TimeRcepcion"]));
            }
            set {
                this["TimeRcepcion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DatoTiempo {
            get {
                return ((double)(this["DatoTiempo"]));
            }
            set {
                this["DatoTiempo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EjeX {
            get {
                return ((int)(this["EjeX"]));
            }
            set {
                this["EjeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int EjeY1 {
            get {
                return ((int)(this["EjeY1"]));
            }
            set {
                this["EjeY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int EjeY2 {
            get {
                return ((int)(this["EjeY2"]));
            }
            set {
                this["EjeY2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int NumDatos {
            get {
                return ((int)(this["NumDatos"]));
            }
            set {
                this["NumDatos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84")]
        public byte DatoEnviado0 {
            get {
                return ((byte)(this["DatoEnviado0"]));
            }
            set {
                this["DatoEnviado0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte DatoEnviadoHi {
            get {
                return ((byte)(this["DatoEnviadoHi"]));
            }
            set {
                this["DatoEnviadoHi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public byte DatoEnviadoLow {
            get {
                return ((byte)(this["DatoEnviadoLow"]));
            }
            set {
                this["DatoEnviadoLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E0")]
        public string dGVtablaD1 {
            get {
                return ((string)(this["dGVtablaD1"]));
            }
            set {
                this["dGVtablaD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E1")]
        public string dGVtablaD2 {
            get {
                return ((string)(this["dGVtablaD2"]));
            }
            set {
                this["dGVtablaD2"] = value;
            }
        }
    }
}
